/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module alu_slice (
  input op1,
  input op2,
  input S,
  input R,
  input cy_in,
  input V,
  output cy_out,
  output result
);
  wire s0;
  assign s0 = ~ ((cy_in & (op1 | op2)) | (op1 & op2) | S);
  assign cy_out = ~ (s0 | R);
  assign result = ((cy_in & op2 & op1) | ((cy_in | op2 | op1) & (V | s0)));
endmodule
