-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    op1: in std_logic;
    op2: in std_logic;
    S: in std_logic;
    R: in std_logic;
    cy_in: in std_logic;
    V: in std_logic;
    cy_out: out std_logic;
    result: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
begin
  s0 <= NOT ((cy_in AND (op1 OR op2)) OR (op1 AND op2) OR S);
  cy_out <= NOT (s0 OR R);
  result <= ((cy_in AND op2 AND op1) OR ((cy_in OR op2 OR op1) AND (V OR s0)));
end Behavioral;
